### ISSUE TITLE
Full backups not being preserved when using partial strategy

### ISSUE THREAD

**Issue by adam8797** [ChaoticTrials/SimpleBackups#39]
### Minecraft version

1.20.x

### Simple Backups version

1.20.1-3.1.7

### (Neo)Forge version

47.3.5

### The latest.log file

Not Relevant

### Issue description

We've had a catastrophic issue in one of the mods on our server, and some world file is corrupted on disk. Not great, but hey, I have simplebackups, I can just reset to a backup.... Except I can't. An older full backup of the world was cleaned up, and the deltas I have mostly rely on that (now deleted) full backup.

See my backups directory:
```
total 30G
drwxr-xr-x  2 amp amp 4.0K Oct 15 19:14 .
drwxr-xr-x 23 amp amp 4.0K Oct  5 21:29 ..
-rw-r--r--  1 amp amp 1.1G Oct 13 14:40 world_2024-10-13_14-39-57.zip
-rw-r--r--  1 amp amp 1.1G Oct 13 15:40 world_2024-10-13_15-39-58.zip
-rw-r--r--  1 amp amp 1.1G Oct 13 16:40 world_2024-10-13_16-39-58.zip
-rw-r--r--  1 amp amp 1.1G Oct 14 00:00 world_2024-10-14_00-00-06.zip
-rw-r--r--  1 amp amp 1.1G Oct 14 01:00 world_2024-10-14_01-00-07.zip
-rw-r--r--  1 amp amp 1.6G Oct 14 02:00 world_2024-10-14_02-00-07.zip
-rw-r--r--  1 amp amp 1.6G Oct 14 20:55 world_2024-10-14_20-54-54.zip
-rw-r--r--  1 amp amp  21G Oct 15 14:46 world_2024-10-15_14-37-16.zip
-rw-r--r--  1 amp amp 200M Oct 15 15:37 world_2024-10-15_15-37-17.zip
-rw-r--r--  1 amp amp 200M Oct 15 19:14 world_2024-10-15_19-14-27.zip
```

I'm storing almost 10GB of backups, which are completely useless as my last full backup was cleaned up. 

Here is my config:

```toml
enabled = true
backupType = "MODIFIED_SINCE_FULL"
fullBackupTimer = 10080 #7 days
backupsToKeep = 10
timer = 60
compressionLevel = -1
sendMessages = true
maxDiskSize = "75 GB"
outputPath = "simplebackups"
noPlayerBackups = false
createSubDirs = false

[mod_compat]
        mc2discord = true
```

So obviously my issue is that I do a full backup every 7 days, and I've told it to keep 10 hourly backups. However, when I setup this configuration I assumed that the full backups would be preserved, and only the deltas would be pruned to 10.  

It seems to me like you'll have to keep at most two full backups in a situation like this. 

```
- Full Alpha
- Delta A
- Delta B
- Delta C
- Delta D
- Full Beta
- Delta 1
- Delta 2
- Delta 3
- Delta 4
- Delta 5
- Delta 6
```

In this example, I have 10 partial backups, and their relevant full backups. When I go to backup, I have to prune one (to hit the 10 limit) so I remove `A`. Keep backing up, and you'd remove `B` then `C` and finally after removing `D` you can also `Full Alpha`
